version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:inception
    build:
      context: ./requirements/nginx/
    networks:
      - custom_network
    volumes:
      - website:/var/www/wordpress
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: on-failure

  mariadb:
    container_name: mariadb
    image: mariadb:inception
    build:
      context: ./requirements/mariadb
    networks:
      - custom_network
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env
    restart: on-failure

  wordpress:
    container_name: wordpress
    image: wordpress:inception
    build:
      context: ./requirements/wordpress
    networks:
      - custom_network
    volumes:
      - website:/var/www/
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: on-failure
  
networks:
  custom_network:
    driver: bridge

volumes:
  website:
    name: website
    driver: local
    driver_opts:
      device: /home/tdeverge/data/wordpress
      o: bind
      type: none

  database:
    name: database
    driver: local
    driver_opts:
      device: /home/tdeverge/data/mariadb
      o: bind
      type: none
